/**
 * Catalog of self-hostable LLM serving stacks you can run locally, next to
 * Ollama — sourced from the awesome-llm-services list (github.com/av/awesome-llm-services).
 *
 * This is a REFERENCE catalog (what you can install), complementing the live
 * discovery scan (what's actually running). Each stack that speaks an
 * OpenAI-compatible or Ollama-native API can then be added as an inference
 * backend and detected by discovery. Install commands are reviewed in the UI
 * first; the desktop app may open them in Terminal only after an explicit
 * operator click, with clipboard fallback if Terminal automation is blocked.
 * Ports/install commands are web-verified (local-stacks-and-models-catalog
 * research).
 */

import type { ProviderKind } from './schema.ts';

export interface LocalStackEntry {
  /** Stable kebab-case id. */
  id: string;
  /** Product name. */
  name: string;
  /** One line: what it is / why pick it. */
  blurb: string;
  /** How a client talks to it. */
  apiKind: ProviderKind | 'other';
  openaiCompatible: boolean;
  /** Primary default localhost port (display + matching the discovery scan). */
  defaultPort?: number;
  /** The provider baseUrl this stack serves on (when addable as a backend). */
  apiBase?: string;
  /** One-line install/run command; the UI reviews it before any Terminal run. */
  install?: string;
  /** One-line start command for an already-installed local stack. */
  start?: string;
  /** One-line uninstall/cleanup command; the UI reviews it before any Terminal run. */
  uninstall?: string;
  /** Operator-facing install complexity for the Settings shortlist. */
  installEase?: 'start-here' | 'easy' | 'guided' | 'advanced' | 'expert';
  /** Short reason behind the installEase label. */
  installNote?: string;
  /** Short reason/limitation for uninstall cleanup. */
  uninstallNote?: string;
  /** Repo / docs URL. */
  homepage: string;
  /** Supported desktop platforms. */
  platforms: Array<'macos' | 'linux' | 'windows'>;
  /** Apple-Silicon-native / especially strong on Mac. */
  appleSilicon?: boolean;
  /** Filter tags (gguf, high-throughput, apple-silicon, low-vram, embeddings…). */
  tags?: string[];
}

/** Web-verified serving stacks, ordered by relevance. */
export const LOCAL_STACKS: LocalStackEntry[] = [
  {"id": "ollama", "name": "Ollama", "blurb": "Easiest local LLM runner; one-command model pull/run with a built-in REST API and OpenAI-compatible shim. Great default for desktops.", "apiKind": "ollama", "openaiCompatible": true, "defaultPort": 11434, "apiBase": "http://127.0.0.1:11434", "install": "brew install ollama && brew services start ollama   # then: ollama run llama3", "uninstall": "brew services stop ollama 2>/dev/null || true; brew uninstall ollama 2>/dev/null || brew uninstall --cask ollama", "installEase": "start-here", "installNote": "Best first-run path: install Ollama, pull one model, scan, then add the backend.", "uninstallNote": "Stops and removes a Homebrew Ollama formula or cask install. App-bundle installs outside Homebrew may need to be removed from Applications separately.", "homepage": "https://github.com/ollama/ollama", "platforms": ["macos", "linux", "windows"], "appleSilicon": true, "tags": ["gguf", "apple-silicon", "easy", "embeddings", "desktop", "start-here"]},
  {"id": "lm-studio", "name": "LM Studio", "blurb": "Polished desktop GUI app for discovering, downloading, and running local LLMs (GGUF + MLX), with a one-click OpenAI-compatible local server and a 'lms' CLI.", "apiKind": "openai-compatible", "openaiCompatible": true, "defaultPort": 1234, "apiBase": "http://127.0.0.1:1234/v1", "install": "brew install --cask lm-studio   # then enable the Local Server (or: lms server start)", "start": "open -a \"LM Studio\"; sleep 2; if [ -x \"$HOME/.lmstudio/bin/lms\" ]; then \"$HOME/.lmstudio/bin/lms\" server start; \"$HOME/.lmstudio/bin/lms\" server status; else printf \"\\nIn LM Studio: download or load a model, start the Local Server on port 1234, then return to IDACC and Scan running.\\n\"; fi", "uninstall": "brew uninstall --cask lm-studio", "installEase": "start-here", "installNote": "Homebrew installs the app only. Open LM Studio, download or load a model, start the Local Server on port 1234, then scan running servers.", "uninstallNote": "Removes the Homebrew cask; downloaded app copies may need manual removal.", "homepage": "https://lmstudio.ai/", "platforms": ["macos", "windows", "linux"], "appleSilicon": true, "tags": ["gui", "desktop", "gguf", "mlx", "metal", "cuda", "model-browser", "no-api-key", "loopback-only", "start-here"]},
  {"id": "llama-cpp", "name": "llama.cpp (llama-server)", "blurb": "Reference C/C++ GGUF inference engine with a built-in HTTP server (llama-server) that speaks the OpenAI chat format natively. Runs almost anywhere.", "apiKind": "openai-compatible", "openaiCompatible": true, "defaultPort": 8080, "apiBase": "http://127.0.0.1:8080/v1", "install": "brew install llama.cpp   # then: llama-server -hf <repo>/<model.gguf> --port 8080", "uninstall": "brew uninstall llama.cpp", "installEase": "guided", "installNote": "Good lightweight server, but you still need to choose a GGUF/model source.", "uninstallNote": "Removes the Homebrew llama.cpp package; downloaded model files are left alone.", "homepage": "https://github.com/ggml-org/llama.cpp", "platforms": ["macos", "linux", "windows"], "appleSilicon": true, "tags": ["gguf", "apple-silicon", "cpu", "low-vram", "embeddings", "vulkan", "guided"]},
  {"id": "vllm", "name": "vLLM", "blurb": "High-throughput GPU serving engine with PagedAttention and continuous batching; the standard for production OpenAI-compatible self-hosting at scale.", "apiKind": "openai-compatible", "openaiCompatible": true, "defaultPort": 8000, "apiBase": "http://127.0.0.1:8000/v1", "install": "python3 -m pip install --user vllm   # then: vllm serve <model> --port 8000", "uninstall": "python3 -m pip uninstall -y vllm", "installEase": "advanced", "installNote": "Linux GPU serving path; not a normal macOS desktop install. Run it on a compatible host with a real model id, then add the API backend here.", "uninstallNote": "Runs against the Python environment opened by Terminal; virtualenv installs should be removed from that environment instead.", "homepage": "https://github.com/vllm-project/vllm", "platforms": ["linux"], "tags": ["high-throughput", "paged-attention", "cuda", "rocm", "batching", "production", "advanced"]},
  {"id": "tgi", "name": "Hugging Face Text Generation Inference (TGI)", "blurb": "Hugging Face's production-grade Rust/Python serving stack with tensor parallelism and continuous batching; ships an OpenAI-compatible Messages API.", "apiKind": "openai-compatible", "openaiCompatible": true, "defaultPort": 8080, "apiBase": "http://127.0.0.1:8080/v1", "install": "docker run --gpus all -p 8080:80 ghcr.io/huggingface/text-generation-inference --model-id <model>", "installEase": "advanced", "installNote": "Linux/NVIDIA-oriented production server. The command is a template: choose a real model id and compatible host before running it.", "homepage": "https://github.com/huggingface/text-generation-inference", "platforms": ["linux"], "tags": ["high-throughput", "batching", "cuda", "production", "docker", "messages-api", "advanced"]},
  {"id": "sglang", "name": "SGLang", "blurb": "High-performance serving engine with RadixAttention prefix caching and structured-output support; strong throughput rival to vLLM for production.", "apiKind": "openai-compatible", "openaiCompatible": true, "defaultPort": 30000, "apiBase": "http://127.0.0.1:30000/v1", "install": "python3 -m pip install --user \"sglang[all]\"   # then: python3 -m sglang.launch_server --model-path <model> --port 30000", "installEase": "advanced", "installNote": "High-throughput server with more setup surface than desktop apps.", "homepage": "https://github.com/sgl-project/sglang", "platforms": ["linux"], "tags": ["high-throughput", "radix-attention", "structured-output", "cuda", "rocm", "production", "advanced"]},
  {"id": "mlx-lm-server", "name": "MLX (mlx_lm.server)", "blurb": "Apple's MLX framework's built-in OpenAI-compatible server (mlx_lm.server) for running LLMs natively on Apple Silicon with Metal acceleration.", "apiKind": "openai-compatible", "openaiCompatible": true, "defaultPort": 8081, "apiBase": "http://127.0.0.1:8081/v1", "install": "python3 -m pip install --user 'urllib3<2' mlx-lm", "start": "python3 -m mlx_lm server --model mlx-community/Llama-3.2-3B-Instruct-4bit --port 8081", "uninstall": "python3 -m pip uninstall -y mlx-lm mlx mlx-metal", "installEase": "easy", "installNote": "Good Apple-Silicon native path if you are comfortable with Python packages. Install adds the Python package only; Start background runs the OpenAI-compatible server on port 8081 so it does not collide with llama.cpp or LocalAI on 8080.", "uninstallNote": "Removes MLX Python packages from the active user Python environment; downloaded Hugging Face model cache files are left alone.", "homepage": "https://github.com/ml-explore/mlx-lm", "platforms": ["macos"], "appleSilicon": true, "tags": ["apple-silicon", "metal", "mlx", "safetensors", "mac-only", "low-vram", "easy"]},
  {"id": "mistral-rs", "name": "mistral.rs", "blurb": "Fast Rust-based inference engine supporting GGUF/GPTQ and full-precision; exposes both OpenAI- and Anthropic-compatible APIs plus a built-in web UI.", "apiKind": "openai-compatible", "openaiCompatible": true, "defaultPort": 1234, "apiBase": "http://127.0.0.1:1234/v1", "install": "cargo install mistralrs-cli --features metal   # then: mistralrs-server --port 1234 ...", "installEase": "advanced", "installNote": "Rust/Cargo path with model/server flags; powerful, but not beginner-first.", "homepage": "https://github.com/EricLBuehler/mistral.rs", "platforms": ["macos", "linux", "windows"], "appleSilicon": true, "tags": ["rust", "gguf", "gptq", "apple-silicon", "cuda", "anthropic-compatible", "advanced"]},
  {"id": "koboldcpp", "name": "KoboldCpp", "blurb": "Single-binary llama.cpp fork with a built-in web UI; popular for local chat/roleplay and storytelling. Exposes KoboldAI plus OpenAI-compatible APIs.", "apiKind": "openai-compatible", "openaiCompatible": true, "defaultPort": 5001, "apiBase": "http://127.0.0.1:5001/v1", "install": "download koboldcpp binary from GitHub releases   # then: ./koboldcpp model.gguf --port 5001", "installEase": "guided", "installNote": "Download-and-run path, but not a CLI install command the app can run for you.", "homepage": "https://github.com/LostRuins/koboldcpp", "platforms": ["macos", "linux", "windows"], "appleSilicon": true, "tags": ["gguf", "single-binary", "ui", "apple-silicon", "roleplay", "multimodal", "guided"]},
  {"id": "jan", "name": "Jan", "blurb": "Open-source desktop ChatGPT alternative (privacy-first, offline) built on the Cortex/llama.cpp engine, with a built-in OpenAI-compatible local API server.", "apiKind": "openai-compatible", "openaiCompatible": true, "defaultPort": 1337, "apiBase": "http://127.0.0.1:1337/v1", "install": "brew install --cask jan   # then Settings > Local API Server > Start Server", "uninstall": "brew uninstall --cask jan", "installEase": "easy", "installNote": "GUI install; remember to start the local API server before scanning.", "uninstallNote": "Removes the Homebrew cask; downloaded app copies may need manual removal.", "homepage": "https://github.com/menloresearch/jan", "platforms": ["macos", "windows", "linux"], "appleSilicon": true, "tags": ["gui", "desktop", "cortex", "llama-cpp", "gguf", "metal", "offline", "privacy", "openai-compat", "easy"]},
  {"id": "gpt4all", "name": "GPT4All", "blurb": "Nomic's privacy-focused desktop app for running local LLMs on consumer CPUs/GPUs, with a built-in (subset) OpenAI-compatible Local API Server.", "apiKind": "openai-compatible", "openaiCompatible": true, "defaultPort": 4891, "apiBase": "http://127.0.0.1:4891/v1", "install": "brew install --cask gpt4all   # then Settings > Application > Enable Local API Server", "installEase": "easy", "installNote": "GUI install; enable its local API server before scanning.", "homepage": "https://github.com/nomic-ai/gpt4all", "platforms": ["macos", "windows", "linux"], "appleSilicon": true, "tags": ["gui", "desktop", "gguf", "cpu", "metal", "localdocs", "rag", "privacy", "loopback-only", "openai-subset", "easy"]},
  {"id": "localai", "name": "LocalAI", "blurb": "Self-hosted, drop-in OpenAI/Anthropic/Ollama-compatible API gateway over multiple backends (llama.cpp, diffusers, whisper, etc.) with a built-in WebUI; runs without a GPU.", "apiKind": "openai-compatible", "openaiCompatible": true, "defaultPort": 8080, "apiBase": "http://127.0.0.1:8080/v1", "install": "docker run -p 8080:8080 --name local-ai -ti localai/localai:latest-cpu", "start": "docker start local-ai", "uninstall": "docker rm -f local-ai", "installEase": "guided", "installNote": "Docker path using LocalAI's CPU quickstart image. If the container already exists, use Start instead of Install, then Scan running.", "uninstallNote": "Stops and removes the local-ai Docker container; model/cache volumes are left alone.", "homepage": "https://localai.io/", "platforms": ["linux", "macos", "windows"], "appleSilicon": true, "tags": ["gguf", "openai-drop-in", "webui", "multi-backend", "cpu", "cuda", "rocm", "embeddings", "image-gen", "whisper", "guided"]},
  {"id": "docker-model-runner", "name": "Docker Model Runner", "blurb": "Docker Desktop/Engine feature (DMR) to pull and run models as OCI artifacts with automatic GPU/memory handling, exposing OpenAI/Anthropic/Ollama-compatible endpoints.", "apiKind": "openai-compatible", "openaiCompatible": true, "defaultPort": 12434, "apiBase": "http://127.0.0.1:12434/engines/v1", "install": "docker desktop enable model-runner --tcp 12434 && docker model run ai/llama3.2", "installEase": "guided", "installNote": "Good if Docker Desktop is already installed; otherwise use Ollama/LM Studio first.", "homepage": "https://docs.docker.com/ai/model-runner/", "platforms": ["macos", "windows", "linux"], "appleSilicon": true, "tags": ["docker", "oci-models", "gguf", "metal", "cuda", "openai-compat", "anthropic-compat", "ollama-compat", "host-tcp", "guided"]},
  {"id": "tabbyapi", "name": "TabbyAPI (ExLlamaV2)", "blurb": "Lightweight FastAPI server wrapping ExLlamaV2/ExLlamaV3 for fast EXL2 quantized inference on consumer GPUs. OpenAI- and KoboldAI-compatible.", "apiKind": "openai-compatible", "openaiCompatible": true, "defaultPort": 5000, "apiBase": "http://127.0.0.1:5000/v1", "install": "git clone https://github.com/theroyallab/tabbyAPI && cd tabbyAPI && ./start.sh", "homepage": "https://github.com/theroyallab/tabbyAPI", "platforms": ["linux", "windows"], "tags": ["exllama", "exl2", "low-vram", "cuda", "quantized", "single-gpu"]},
  {"id": "aphrodite-engine", "name": "Aphrodite Engine", "blurb": "High-throughput vLLM fork (PagedAttention + continuous batching) with extensive quantization support and rich samplers; OpenAI-compatible serving engine from PygmalionAI.", "apiKind": "openai-compatible", "openaiCompatible": true, "defaultPort": 2242, "apiBase": "http://127.0.0.1:2242/v1", "install": "python3 -m pip install --user aphrodite-engine && aphrodite run NousResearch/Meta-Llama-3.1-8B-Instruct", "homepage": "https://github.com/aphrodite-engine/aphrodite-engine", "platforms": ["linux"], "tags": ["gguf", "high-throughput", "paged-attention", "quantization", "cuda", "vllm-fork", "samplers"]},
  {"id": "ik-llama-cpp", "name": "ik_llama.cpp", "blurb": "Performance-focused fork of llama.cpp by ikawrakow with advanced quants (IQK), faster CPU/CUDA kernels, and MoE optimizations; ships the same llama-server with OpenAI-compatible API.", "apiKind": "openai-compatible", "openaiCompatible": true, "defaultPort": 8080, "apiBase": "http://127.0.0.1:8080/v1", "install": "git clone https://github.com/ikawrakow/ik_llama.cpp && cd ik_llama.cpp && cmake -B build && cmake --build build --config Release && ./build/bin/llama-server -m model.gguf --port 8080", "homepage": "https://github.com/ikawrakow/ik_llama.cpp", "platforms": ["linux", "macos", "windows"], "appleSilicon": true, "tags": ["gguf", "llama-cpp-fork", "cpu", "cuda", "metal", "moe", "iqk-quants", "low-vram"]},
  {"id": "ktransformers", "name": "KTransformers", "blurb": "CPU/GPU-hybrid engine from kvcache-ai that offloads MoE experts to CPU/RAM, letting huge models (DeepSeek, Kimi, GLM) run on a single GPU + big RAM.", "apiKind": "openai-compatible", "openaiCompatible": true, "defaultPort": 10002, "apiBase": "http://127.0.0.1:10002/v1", "install": "python3 -m pip install --user ktransformers   # then: ktransformers --model_path <model> --port 10002", "homepage": "https://github.com/kvcache-ai/ktransformers", "platforms": ["linux", "windows"], "tags": ["moe", "cpu-offload", "low-vram", "deepseek", "large-models", "cuda"]},
  {"id": "modular-max", "name": "Modular MAX", "blurb": "Modular's MAX inference engine + serving framework (Mojo/MAX graph) with a one-command OpenAI-compatible endpoint; high-performance GPU serving as a vLLM alternative.", "apiKind": "openai-compatible", "openaiCompatible": true, "defaultPort": 8000, "apiBase": "http://127.0.0.1:8000/v1", "install": "python3 -m pip install --user modular && max serve --model-path modularai/Llama-3.1-8B-Instruct-GGUF", "homepage": "https://docs.modular.com/max/", "platforms": ["linux", "macos"], "appleSilicon": true, "tags": ["high-throughput", "gpu", "mojo", "max-graph", "embeddings", "cuda", "gguf"]},
  {"id": "nexa-sdk", "name": "Nexa SDK", "blurb": "Cross-platform local inference SDK/CLI with day-0 model support across GPU, NPU, and CPU; multimodal (LLM/VLM/ASR/TTS/image) with an OpenAI-compatible 'nexa serve'.", "apiKind": "openai-compatible", "openaiCompatible": true, "defaultPort": 8000, "apiBase": "http://127.0.0.1:8000/v1", "install": "brew install nexadb   # or: python3 -m pip install --user nexaai --prefer-binary --index-url https://nexaai.github.io/nexa-sdk/whl/cpu --extra-index-url https://pypi.org/simple", "homepage": "https://github.com/NexaAI/nexa-sdk", "platforms": ["macos", "linux", "windows"], "appleSilicon": true, "tags": ["npu", "gguf", "mlx", "multimodal", "vlm", "asr", "tts", "cross-platform", "metal", "qualcomm-npu"]},
  {"id": "lemonade", "name": "Lemonade Server", "blurb": "AMD's privacy-first local AI server optimized for Ryzen AI NPU + iGPU (hybrid execution); bundles llama.cpp and exposes an OpenAI-compatible API.", "apiKind": "openai-compatible", "openaiCompatible": true, "defaultPort": 8000, "apiBase": "http://127.0.0.1:8000/api/v1", "install": "python3 -m pip install --user lemonade-sdk   # then: lemonade-server serve   (or download the installer)", "homepage": "https://github.com/lemonade-sdk/lemonade", "platforms": ["windows", "linux", "macos"], "appleSilicon": true, "tags": ["amd", "npu", "ryzen-ai", "gguf", "apple-silicon", "multimodal"]},
  {"id": "airllm", "name": "AirLLM", "blurb": "Memory-optimization inference library that runs 70B (even 405B) models on a single 4GB GPU via layer-by-layer disk streaming; a Python library, not a server.", "apiKind": "other", "openaiCompatible": false, "install": "python3 -m pip install --user airllm", "homepage": "https://github.com/lyogavin/airllm", "platforms": ["linux", "macos", "windows"], "appleSilicon": true, "tags": ["low-vram", "layer-streaming", "library", "no-server", "70b-on-4gb", "metal", "quantization"]},
];

/** Default stack shortlist for the Settings page. The full catalog remains
 *  available to code, but the UI should not push long-tail servers by default. */
const SETTINGS_STACK_SHORTLIST = [
  'ollama',
  'lm-studio',
  'gpt4all',
  'docker-model-runner',
];
export const TOP_LOCAL_STACKS: LocalStackEntry[] = SETTINGS_STACK_SHORTLIST
  .map((id) => LOCAL_STACKS.find((s) => s.id === id))
  .filter((s): s is LocalStackEntry => Boolean(s));
